// Selectors
const TABLE_WRAPPER = '.data-table__wrapper'
const INVOICE_ROW = 'div.invoice-line-items-table__row'
const UNIT_FIELD = '.invoice-line-items-table-form-row__unit-field'
const UNIT_BUTTON = 'button.form-select-field-2__trigger'
const UNIT_TITLE = '.select-field-standard-item__title'
const QTY_FIELD = '.invoice-line-items-table-form-row__quantity-field'
const RATE_FIELD = '.invoice-line-items-table-form-row__unit-price-field'
const POPOVER = '.popover-content__body'
const POPOVER_OPTIONS = '.select-field-standard-item__title'
const INVOICE_TOTAL = '.invoice-total__total-value'
const ROAM_ASSISTANT_WRAPPER = '.roam-assistant--wrapper'
const ROAM_CONVERT_GO = '#roam-convert-go'
